name: Build and deploy to GKE

on:
  push:
    branches: [ main ]

env:
  CLUSTER_NAME: multi-k8s
  CLUSTER_ZONE: asia-southeast1
  PROJECT_ID: multi-k8s-497915
  DEPLOYMENT_NAME: my-app

jobs:
  build-test-and-deploy:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        include:
          - name: gateway
            context: ./nginx
            docker_repo: sojucr7/gateway
          - name: client
            context: ./client
            docker_repo: sojucr7/client
          - name: worker
            context: ./worker
            docker_repo: sojucr7/worker
          - name: server
            context: ./server
            docker_repo: sojucr7/api

    steps:
      - uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build dev image (frontend only)
        if: matrix.name == 'client'
        uses: docker/build-push-action@v5
        with:
          context: ${{ matrix.context }}
          file: ${{ matrix.context }}/Dockerfile.dev
          push: false
          tags: test-client:latest

      - name: Run npm test (frontend only)
        if: matrix.name == 'client'
        run: docker run --rm -e CI=true test-client:latest npm test -- --watchAll=false

      - name: Build & push image
        uses: docker/build-push-action@v5
        with:
          context: ${{ matrix.context }}
          file: ${{ matrix.context }}/Dockerfile
          push: true
          tags: |
            ${{ matrix.docker_repo }}:latest
            ${{ matrix.docker_repo }}:${{ github.sha }}

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v2

      - name: Get GKE credentials
        run: |
          gcloud container clusters get-credentials \
          $CLUSTER_NAME \
          --zone $CLUSTER_ZONE \
          --project $PROJECT_ID